int fact(int n);
double prRoll(int* arr);
int** dicePatterns(int n);
int contains(int* arr, int e, int size);
int** choosePatterns(int r);
int yahtzee(int* dice, int up);
int ones(int* dice, int up);
int twos(int* dice, int up);
int threes(int* dice, int up);
int fours(int* dice, int up);
int fives(int* dice, int up);
int sixes(int* dice, int up);
int sum(int* dice);
int three_of_a_kind(int* dice, int up);
int four_of_a_kind(int* dice, int up);
int fullhouse(int* dice, int up);
int small_straight(int* dice, int up);
int large_straight(int* dice, int up);
int chance(int* dice, int up);
int code(int* cats, int up, int size);
int* append(int* cats, int c, int size);
int* extendDice(int* dice, int d, int size);
int* removeDice(int* dice, int d, int size);
int find(int** lib, int* row, int row_size, int entries);